include: package:linteo/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
    - architecture_linter
  errors:
    body_might_complete_normally_nullable: "ignore"
    strict_raw_type: "ignore"
    no_runtimetype_tostring: "ignore"
    multiple_plugins: "ignore"

  exclude:
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.cached.dart"
    - "**.g.dart"
    - "**.mocks.dart"
    - "**.config.dart"
    - "lib/generated_plugin_registrant.dart"
    - "build/**"
    - "assets/**"
    - "ios/**"
    - "android/**"
    - "lib/presentation/gen/**"
    - "distribution/**"

linter:
  rules:
    avoid_annotating_with_dynamic: false
    avoid_positional_boolean_parameters: false
    flutter_style_todos: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  rules:
    - avoid-global-state
    - avoid-nested-conditional-expressions
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-equal-then-else
    - no-object-declaration
    - avoid-shrink-wrap-in-lists
    - always-remove-listener
    - avoid-returning-widgets:
        ignored-annotations:
          - usedInListView
          - conditionalWidget
    - avoid-unnecessary-setstate

architecture_linter:
  excludes:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.cached.dart"
    - "**.gr.dart"
    - "**.mocks.dart"
    - "test/**"

  lint_severity: warning

  layers:
    - &dataLayer
      name: "Data"
      path: "lib/data"
    - &domainLayer
      name: "Domain"
      path: "lib/domain"
    - &presentationLayer
      name: "Presentation"
      path: "lib/presentation"

  bannedImports:
    - layer: *domainLayer
      banned:
        - *presentationLayer
        - *dataLayer
    - layer: *presentationLayer
      banned:
        - *dataLayer
    - layer: *dataLayer
      banned:
        - *presentationLayer
