name: iteo_libraries_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: 1.1.0
  theme_tailor: 2.0.2
  theme_tailor_annotation: ^2.0.2
  hooked_bloc: ^1.5.0
  flutter_bloc: 8.1.3
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.4
  get_it: ^7.6.4
  auto_size_text: 3.0.0
  shared_preferences: 2.2.2
  rxdart: 0.27.7
  provider: 6.1.1
  flutter_hooks: ^0.20.4
  gap: 3.0.1
  flutter_svg: 2.0.9
  easy_localization: 3.0.3
  json_annotation: 4.8.1
  cached_annotation: 1.6.0
  uni_links: 0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  cached: 1.6.1
  build_runner: 2.4.6
  freezed: ^2.4.6
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  linteo: ^1.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/translations/