name: iteo_libraries_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc_test: ^9.1.6
  http: 1.2.1
  theme_tailor: 2.0.2
  theme_tailor_annotation: ^2.0.2
  hooked_bloc: ^1.5.0
  flutter_bloc: 8.1.3
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.4
  get_it: ^7.6.4
  auto_size_text: 3.0.0
  shared_preferences: 2.2.2
  rxdart: 0.27.7
  provider: 6.1.1
  flutter_hooks: ^0.20.4
  gap: 3.0.1
  flutter_svg: 2.0.9
  easy_localization: 3.0.7
  json_annotation: 4.8.1
  cached_annotation: 1.7.0
  uni_links: 0.5.1
  fimber: ^0.7.0
  equatable: ^2.0.5
  drift: ^2.16.0
  sqlcipher_flutter_libs: ^0.6.0
  sqlite3: ^2.3.0
  path_provider: ^2.0.0
  path: ^1.9.0
  flutter_secure_storage: ^9.0.0
  injectable: ^2.4.1
  chopper: ^7.2.0
  collection: ^1.18.0
  connecteo: ^3.0.0
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  cached: 1.7.0
  drift_dev: 2.16.0
  build_runner: 2.4.9
  freezed: ^2.4.6
  injectable_generator: ^2.6.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  linteo: ^1.1.0
  chopper_generator: ^7.3.0
  mockito: ^5.0.15
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/